version: 1.2.{build}
image:
- Visual Studio 2017
- Ubuntu1804

configuration: 
- Debug
- Release

platform:
 - x86
 - x64
 
init:
 - sh: if [ "${CONFIGURATION}" = "Debug" ] ; then exit 0; fi
 - sh: if [ "${PLATFORM}" = "x86" ]; then exit 0; fi 
 
install:
- cmd: echo %APPVEYOR_BUILD_FOLDER%

- cmd: git submodule update --init
    
- cmd: cd %APPVEYOR_BUILD_FOLDER%\libusb
    
- cmd:   git apply ..\msvc\0001-Static-link-C-library.patch
    
- cmd:    cd ..
 
- sh: sudo apt-get update

- sh: sudo apt-get --yes --force-yes install libusb-1.0-0-dev

- sh: sudo apt-get --yes --force-yes install libzip-dev

- sh: sudo apt-get --yes --force-yes install libbz2-dev
    
- sh: sudo apt-get --yes --force-yes install asciidoc
    
- sh: sudo apt-get --yes --force-yes install rename

build_script:

- cmd: msbuild %APPVEYOR_BUILD_FOLDER%/msvc/uuu.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

- cmd: if exist %APPVEYOR_BUILD_FOLDER%\x64\release\dll\uuu.exe  cp %APPVEYOR_BUILD_FOLDER%\x64\release\dll\uuu.exe  %APPVEYOR_BUILD_FOLDER%\uuu.exe

- cmd: if exist %APPVEYOR_BUILD_FOLDER%\x64\release\dll\libusb-1.0.dll cp %APPVEYOR_BUILD_FOLDER%\x64\release\dll\libusb-1.0.dll  %APPVEYOR_BUILD_FOLDER%\libusb-1.0.dll
   
- sh: cmake .
- sh: make
     
- sh: git clone https://github.com/NXPmicro/mfgtools.wiki.git
    
- sh: cd mfgtools.wiki
    
- sh: rename -f 's/\.asciidoc$//' *
    
- sh: echo "<revhistory>" > UUU-docinfo.xml
    
- sh: git log -n25 --reverse --format="format:<revision><revnumber>%h</revnumber><date>%cd</date><authorinitials>%an</authorinitials><revremark>%s%n%b</revremark></revision>" >> UUU-docinfo.xml
    
- sh: echo "</revhistory>" >> UUU-docinfo.xml
    
- sh: a2x -L -a docinfo UUU-docinfo.xml
    
artifacts:
- path: uuu.exe
- path: uuu/uuu
- path: libusb-1.0.dll
- path: mfgtools.wiki/UUU.pdf

before_deploy:
- cmd: ''
deploy:
- provider: GitHub
  description: prebuild for $(APPVEYOR_REPO_COMMIT) \n\n $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: SWWVkwSfPyVIaPChBBl+uAA3Fau9Rl5iNPQ9VRL8yyggXvc6wPcr/O9iXBMVM7Ju
  artifact: uuu.exe;  libusb-1.0.dll; uuu/uuu; mfgtools.wiki/UUU.pdf
  draft: true
